language: node_js
node_js:
  - "lts/*"
script:
  - node index.js
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  target-branch: master
  verbose: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
