language: node_js
node_js:
  - "lts/*"
script:
  - node add.js
  - node index.js
  - rvm install 2.6
  - rvm use 2.6
  - gem install bundler
  - bundle install
  - bundle exec jekyll doctor
  - bundle exec jekyll build --source docs --destination docs/_site
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  target-branch: master
  verbose: true
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
